# Panel classes {#panels}

```{r, include=FALSE}
source("R/symbols.R")
```

## Overview

The types of builtin panels available to compose an `r Biocpkg("iSEE")` app are defined as a hierarchy of S4 classes.

<!-- TODO Replace the bullet list below by a figure, like a filesystem tree. -->

- `Panel` `r .virtual_panel_symbol`
    - `DotPlot` `r .virtual_panel_symbol`
        - `ColumnDotPlot` `r .virtual_panel_symbol`
            - `ReducedDimensionPlot`
            - `ColumnDataPlot`
            - `FeatureAssayPlot`
        - `RowDotPlot` `r .virtual_panel_symbol`
            - `RowDataPlot`
            - `SampleAssayPlot`
    - `Table` `r .virtual_panel_symbol`
        - `RowTable` `r .virtual_panel_symbol`
            - `RowDataTable`
        - `ColumnTable` `r .virtual_panel_symbol`
            - `ColDataTable`
    - `ComplexHeatmapPlot`

Some of those classes are "virtual" (indicated by `r .virtual_panel_symbol`), meaning that they cannot be directly instanciated as panels in the GUI.
Instead, virtual panel classes define families of panels that share groups of properties.
As such, virtual classes are meant to be used as the parent of concrete classes that share the associated properties.

In contrast, concrete classes must define fully-functional panels that can be embedded in a GUI, interact with other panels, receive and process data, and generate an output such as a plot or a table, accompanied by the associated R code to display in the code tracker for reproducibility.

## The Panel class

The top-most class is called `Panel`.
It is a virtual class that defines the core properties common to any panel - existing or future - that may be displayed in the interface.

Refer to `help("Panel-class", "iSEE")` for more information about the slots and methods provided by this class.

## The DotPlot and Table panel families

The virtual class `Panel` is directly derived into two major virtual sub-classes:

- `DotPlot`
- `Table`

Those classes introduce properties that are specific to distinct subsets of panel types.

The class `DotPlot` introduces parameters specific to panels where the output is a `ggplot` object and each row in the data-frame is represented as a point in a plot.
Refer to `help("DotPlot-class", "iSEE")` for more information.

The class `Table` introduces parameters specific to panels where the main output is a data-frame directly displayed as a table in the GUI.
Refer to `help("Table-class", "iSEE")` for more information.

As a special case, the class `ComplexHeatmapPlot` defines a concrete panel class that directly extends the class `Panel`, as it introduces a set of parameters distinct from both the `DotPlot` and `Table` panel families.
This panel class is described in further details in the section [The ComplexHeatmapPlot panel class](#complexheatmapplot-class).

<!-- TODO: properties introduced by the DotPlot class -->

<!-- TODO: properties introduced by the Table class -->

## The ColumnDotPlot and RowDotPlot panel families

<!-- TODO: properties introduced by the ColumnDotPlot class -->

<!-- TODO: properties introduced by the RowDotPlot class -->

## Built-in ColumnDotPlot panel classes

<!-- TODO: properties introduced by the ReducedDimensionPlot class -->

<!-- TODO: properties introduced by the ColumnDataPlot class -->

<!-- TODO: properties introduced by the FeatureAssayPlot class -->

## Built-in RowDotPlot panel classes

<!-- TODO: properties introduced by the RowDataPlot class -->

<!-- TODO: properties introduced by the SampleAssayPlot class -->

## The ColumnTable and RowTable panel families

<!-- TODO: properties introduced by the ColumnTable class -->

<!-- TODO: properties introduced by the RowTable class -->

## Built-in ColumnTable panel classes

<!-- TODO: properties introduced by the RowDataTable class -->

## Built-in RowTable panel classes

<!-- TODO: properties introduced by the ColDataTable class -->

## The ComplexHeatmapPlot panel class {#complexheatmapplot-class}

This type of panel introduces parameters specific to panels where the output is a `Heatmap` object from the `r Biocpkg("ComplexHeatmap")` package.
In this panel, each row represents a feature and each column represents a sample in the `se` object.

<!-- TODO: properties introduced by the ComplexHeatmapPlot class -->
