# The iSEE server {#server}

## Panel classes

### Overview

The types of panels available to compose an `r Biocpkg("iSEE")` app are defined as a hierarchy of S4 classes.

<!-- TODO Replace the bullet list below by a figure, like a filesystem tree. -->

- Panel
  - DotPlot
    - ColumnDotPlot
      - RedDimPlot
      - ColDataPlot
      - FeatAssayPlot
    - RowDotPlot
      - RowDataPlot
      - SampAssayPlot
  - Table
    - RowTable
      - RowStatTable
    - ColumnTable
      - ColStatTable
  - HeatMapPlot

### The Panel class

The top-most class is called `Panel`.
It defines the core properties common to any panel - existing or future - that may be displayed in the interface.

|   |   |
| - | - |
| `PanelId` | Integer index indicating the i^th^ panel of a given type. |
| `PanelHeight` | Height of the panel, in pixels. |
| `PanelWidth` | Width of the panel, an integer value indicating the number of columns to use, from 1 to 12. |
| `SelectBoxOpen` | Logical value indicating if the _Selection parameters_ box of the panel is open when the app starts. |
| `SelectByPlot` | Encoded name of the panel from which to receive a selection of data points. |
| `SelectMultiType` | Keyword indicating the method to deal with multiple incoming selections of data points. |
| `SelectMultiSaved` | Integer index indicating a single data point selection to use, among multiple incoming selections. |

The `Panel` class is directly derived into three subtypes:

- DotPlot
- Table
- HeatMapPlot

## The app memory

The app `memory` is a list of instances of those classes, which keeps track of the order in which individual panels are displayed in the GUI.

## The panel API

### .cacheCommonInfo

Each individual panel (e.g., _RedDimPlot_) and family of panels (e.g., _ColDotPlot_) defines a `.cacheCommonInfo` function.

which is returned by the top-most `.cacheCommonInfo,Panel-method` signature


This function is called for each panel in memory when the app is initialized.
It allows the app to efficienly compute a single time common information that only depends on the input `se` object, and may be frequently reused during the runtime of the app.
The information is cached in the `se` object itself, 

For instance, the `RedDimPlot` panel type caches the available reduced dimension names available in the `se` object.

### .refineParameters

Each panel defines a `.refineParameters` function.
