# The app server {#server}

## Reactive objects {#robjects}

<!-- TODO
A general description of the purpose of reactive values in rObjects would probably be enough.
I don't think developers need details about each individual value.

Some examples values manually collected from iSEE-main.R:
- rerender
- rerendered
- paste0(mode, id)
- paste0(mode, id, "_", .panelLinkInfo)
- paste0(mode, id, "_", .panelGeneralInfo)
- paste0(mode, id, "_", .selectMultiSaved)
- paste0(mode, id, "_repopulated")
- paste0(mode, id, "_reactivated")
- paste0(mode, id, "_resaved")
-->

## Persistent (non-reactive) objects

<!-- TODO
A description of the purpose of pObjects.
In particular, memory and coordinates are key to highlight, although they will be described in further details in dedicated sections.

Some examples:
- memory
- counter
- commands
- coordinates
- cached_info
- .voiceActivePanel
-->

## The app memory {#memory}

The app `memory` is a list of instances created from available panel classes, which defines the order in which individual panels are displayed in the GUI.

## The panel API {#panel-api}

### .cacheCommonInfo

Each individual panel type (e.g., _Reduced dimension plot_) and family of panel types (e.g., _Column dot plot_) defines a `.cacheCommonInfo` function.

This function is called for each panel instance in memory when the app is initialized.
It allows the app to efficiently compute a single time common information that only depends on the input `se` object, and may be frequently reused during the runtime of an app.

Following the hierarchy of panel types, each call to the signature takes a panel instance `x` and the `se` object, and caches common information relevant to all instances of that panel type in the `se` object itself, before calling `callNextMethod()` to invoke the next parent signature.

The top-most signature - for the `Panel` class - returns the `se` object that contains all the cached information.

Note that this function only populates the cache for the first panel of each type; it is a no-op if the common cache has already been initialized.

### .refineParameters

Each individual panel type (e.g., _Reduced dimension plot_) and family of panel types (e.g., _Column dot plot_) defines a `.refineParameters` function.

This function is called for each panel instance in memory when the app is initialized, and also when a new panel is added to the GUI.
It inspects the parameters of a given panel instance, and replaces invalid parameters with sensible values for a given `se` object.

Following the hierarchy of panel types, each call to the signature takes an instance `x` and the `se` object, and first calls `callNextMethod()` to invoke the next parent signature, to refine generic parameters before processing specific ones.

The called signature ultimately returns the updated instance panel `x`, or `NULL` if the panel instance is not available for this app.

## Initialization of the app server

The app server is initialized as soon as a valid `se` object is provided.
This can be either in the call to `iSEE(se)` or using the Shiny file upload button in apps that were launched without providing the `se` arguments, e.g., `iSEE()`.

The `initialize_server` function takes the `se` object and the list holding reactive values used to trigger re-rendering of the GUI, as described [above](#robjects).

The very first step invokes the function `.sanitize_SE_input` on the `se` object.
This function coerces the `se` to `SingleCellExperiment`, flattens nested DataFrames, adds row and column names, and removes other non-atomic fields.
In addition, it also sanitizes the `SingleCellExperiment` object by moving internal fields into the column- or row-level metadata, making them visible in the _Column statistics table_ and _Row statistics table_ panels, respectively. The function returns both the sanitized `se` object that will be used by the app, and the list of R commands that will be displayed in the code tracker for users.

Next, the server invokes the `checkColormapCompatibility` function.
This function takes the `se` object and the optioanl `colormap` provided to `iSEE()`, and carries out a number of compatibility checks between the two objects.
The function collects a character vector of issue messages that are displayed - if any - as warning messages in GUI during initialization.

<!-- TODO: something about setting up memory, once the current TEST code is replaced. -->

Next, the `.cacheCommonInfo` and `.refineParameters` are successively invoked on each panel instance initialized in the app memory.
As described in a separate section [above](#panel-api), the first function precomputes and caches information specific to the `se` object and frequently used throughout the runtime of the app.
The second function ensures that each panel instance is initialized with valid parameters; it replaces any invalid parameters with sensible values for a given `se` object.

<!-- TODO: something, once we deal with user-supplied panel IDs -->

Next, persistent (non-reactive) objects are initialized:

- the app `memory` (see this [section](#memory))
- the count of panels of each type, used to assign increasing ID to new panel instances
- the list of commands to display in the code tracker for each panel instance
- the list of data point coordinates selectable in each panel instance^[Data points downsampled for rendering speed performance remain selectable, even though they are not visible in the plot.]
- a list of miscellaneous cached information^[The plot that contain the legend keys of _Heatmap_ panels is currently cached as miscellaneous information retrieved separately when rendering the GUI.]

<!-- TODO: something about rObjects -->

<!-- TODO: something about the various kinds of observers -->
